# monsieur_biz_rich_editor_plugin:
#     resource: "@MonsieurBizSyliusRichEditorPlugin/Resources/config/routing.yaml"

monsieurbiz_richeditor_admin:
    resource: "@MonsieurBizSyliusRichEditorPlugin/Resources/config/routing/admin.yaml"
    prefix: /%sylius_admin.path_name%

# monsieurbiz_richeditor_admin:
#     resource: "@MonsieurBizSyliusRichEditorPlugin/Resources/config/routing/admin.yaml"
#     prefix: /%sylius_admin.path_name%
